[theme]
primaryColor = "#800080"         # ม่วงเข้ม Thai Airways
backgroundColor = "#f8f0ff"      # ม่วงอ่อนเบาๆ
secondaryBackgroundColor = "#e0d4ec"  # เทาม่วงกลมกลืน
textColor = "#2c003e"            # ม่วงดำ อ่านง่าย
font = "sans serif"
