[theme]
primaryColor = "#5c2a9d"              # ม่วงเข้ม royal purple
backgroundColor = "#f3eefc"           # ม่วงอ่อนอมเทา
secondaryBackgroundColor = "#b39ddb"  # เทาอมม่วง (sidebar, card) #d8c8ec
textColor = "#1e0b38"                 # เทาดำ อ่านง่ายบนพื้นม่วง
font = "sans serif"
